# Generated by Django 2.1 on 2020-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200318_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='removed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
