# Generated by Django 2.1 on 2020-03-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['creat_time', 'id']},
        ),
    ]
