# Generated by Django 2.1 on 2020-03-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200319_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Page',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-creat_time', 'id']},
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
    ]
